const MAX_HEIGHT = 100;
const PIPE_SPEED = 0.1;
const PIPE_WIDTH = 10;
const BIRD_WIDTH = 15;
const BIRD_HEIGHT = (BIRD_WIDTH / 17) * 12;
const GAP_HEIGHT = 30;

export {
  MAX_HEIGHT,
  PIPE_SPEED,
  PIPE_WIDTH,
  BIRD_WIDTH,
  BIRD_HEIGHT,
  GAP_HEIGHT
};
